
version: '3.3'

services:
  database:
    container_name: database-chess-app
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php-chess-app
    build:
      context: ./php
    environment:
        - DATABASE_URL=mysql://db_user:db_password@database/db_name
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/var/www/chess-app

    depends_on:
      - database

  nginx:
    container_name: nginx-chess-app
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/chess-app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  
  frontend:
    container_name: frontend-chess-app
    image: node:20
    ports: 
      - 5173:5173
    working_dir: /app
    volumes:
      - ./frontend:/app
    entrypoint: ["bash"]
    command: ["-c", "npm install; npm run dev"]