nelmio_cors:
    defaults:
    paths:
            '^/':
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                expose_headers: ['*']
                max_age: 3600